import {SPIFile} from "../../src/models/parsed-si-file";

export const SINGLE_SERVICE_PARSED_SPI_FILE: SPIFile = {
    declaration: {version: "1.0", encoding: "UTF-8"}, services: [{
        shortName: "Radio 24",
        mediumName: "Radio 24",
        longName: "Radio 24 - #dasischzüri",
        shortDescription: {lang: "fr", text: "Radio 24 - #dasischzüri"},
        bearer: [{
            id: "fm:4e1.4f15.09210",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:ch.4f15.09210",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:4e1.4f15.09940",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:ch.4f15.09940",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:4e1.4f15.09610",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:ch.4f15.09610",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:4e1.4f15.09230",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:ch.4f15.09230",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:4e1.4f15.08760",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:ch.4f15.08760",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:4e1.4f15.09690",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:ch.4f15.09690",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:4e1.4f15.10280",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:ch.4f15.10280",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:4e1.4f15.09580",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:ch.4f15.09580",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:4e1.4f15.09340",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:ch.4f15.09340",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "http://icecast.radio24.ch/radio24",
            cost: 100,
            offset: 2000,
            mimeValue: "audio/mpeg",
            bitrate: "128",
        }, {
            id: "fm:4e1.4f15.09810",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:ch.4f15.09810",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {
            id: "fm:4e1.4f15.09000",
            cost: 50,
            offset: null,
            mimeValue: null,
            bitrate: null,
        }, {id: "fm:ch.4f15.09000", cost: 50, offset: null, mimeValue: null, bitrate: null}],
        genre: [{text: "Pop", href: "urn:tva:metadata:cs:ContentCS:2011:3.6.4.1"}, {
            text: "Pop-rock",
            href: "urn:tva:metadata:cs:ContentCS:2011:3.6.4",
        }, {text: "Local/Regional", href: "urn:tva:metadata:cs:ContentCS:2011:3.1.1.11"}, {
            text: "News",
            href: "urn:tva:metadata:cs:ContentCS:2011:3.1.1",
        }],
        link: [{
            url: "http://radio24.ch/",
            mimeValue: "text/html",
            lang: "de",
            uri: "http://radio24.ch/",
            description: null,
        }, {url: null, mimeValue: null, lang: null, uri: null, description: null}],
        mediaDescription: [{
            height: 32,
            width: 32,
            type: "logo_colour_square",
            url: "http://static.chrd24.radio.ebu.io/32x32/fc8e6e2d-e022-48f9-9c4d-4374c4b5bac6.png",
        }, {
            height: 32,
            width: 112,
            type: "logo_colour_rectangle",
            url: "http://static.chrd24.radio.ebu.io/112x32/fc8e6e2d-e022-48f9-9c4d-4374c4b5bac6.png",
        }, {
            height: 128,
            width: 128,
            type: "logo_unrestricted",
            url: "http://static.chrd24.radio.ebu.io/128x128/fc8e6e2d-e022-48f9-9c4d-4374c4b5bac6.png",
        }, {
            height: 240,
            width: 320,
            type: "logo_unrestricted",
            url: "http://static.chrd24.radio.ebu.io/320x240/fc8e6e2d-e022-48f9-9c4d-4374c4b5bac6.png",
        }, {
            height: 600,
            width: 600,
            type: "logo_unrestricted",
            url: "http://static.chrd24.radio.ebu.io/600x600/fc8e6e2d-e022-48f9-9c4d-4374c4b5bac6.png",
        }],
        radiodns: {fqdn: "radio24.chrd24.radio.ebu.io", serviceIdentifier: "ebu203chrd24"},
        keywords: null,
    }],
    serviceProvider: {
        geolocation: {country: "ch"},
        link: [{
            url: "http://radio24.ch/",
            mimeValue: "text/html",
            lang: "de",
            uri: "http://radio24.ch/",
            description: "Radio 24 Webpage",
        }, {url: null, mimeValue: null, lang: null, uri: null, description: null}, {
            url: null,
            mimeValue: null,
            lang: null,
            uri: null,
            description: null,
        }],
        shortName: {lang: "de", text: "Radio 24"},
        mediumName: {lang: "de", text: "Radio 24 AG"},
        longName: {lang: "de", text: "Radio 24 AG"},
        shortDescription: {lang: "de", text: "Radio 24 AG"},
        mediaDescription: [{
            type: "logo_colour_square",
            width: 32,
            height: 32,
            url: "http://static.chrd24.radio.ebu.io/32x32/fc8e6e2d-e022-48f9-9c4d-4374c4b5bac6.png",
        }, {
            type: "logo_colour_rectangle",
            width: 112,
            height: 32,
            url: "http://static.chrd24.radio.ebu.io/112x32/fc8e6e2d-e022-48f9-9c4d-4374c4b5bac6.png",
        }, {
            type: "logo_unrestricted",
            width: 128,
            height: 128,
            url: "http://static.chrd24.radio.ebu.io/128x128/fc8e6e2d-e022-48f9-9c4d-4374c4b5bac6.png",
        }, {
            type: "logo_unrestricted",
            width: 320,
            height: 240,
            url: "http://static.chrd24.radio.ebu.io/320x240/fc8e6e2d-e022-48f9-9c4d-4374c4b5bac6.png",
        }, {
            type: "logo_unrestricted",
            width: 600,
            height: 600,
            url: "http://static.chrd24.radio.ebu.io/600x600/fc8e6e2d-e022-48f9-9c4d-4374c4b5bac6.png",
        }],
        keywords: null,
    },
};
